name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          CI: true

      - name: Create release
        if: success() && github.event_name == 'push'
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: $
          NPM_TOKEN: $
